default: &default
  adapter: postgresql
  pool: 5000
  timeout: 5000
  database: open_api_demo
  username: postgres
  host: localhost
  port: 5432

production:
  <<: *default

test:
  <<: *default
  database: open_api_demo_test

development:
  <<: *default
  database: open_api_demo_dev
